--------------------------------------------------------
--  File created - Sunday-March-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LOCATION" 
   (	"LOCATION_KEY" VARCHAR2(45 BYTE), 
	"STREET" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"CITY" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"PROVINCE_OR_STATE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"COUNTRY" VARCHAR2(45 BYTE) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.LOCATION
SET DEFINE OFF;
Insert into SYSTEM.LOCATION (LOCATION_KEY,STREET,CITY,PROVINCE_OR_STATE,COUNTRY) values ('l1','kailash','delhi','delhi','india');
Insert into SYSTEM.LOCATION (LOCATION_KEY,STREET,CITY,PROVINCE_OR_STATE,COUNTRY) values ('l2','saket','islamabad','islamabad','pakistan');
Insert into SYSTEM.LOCATION (LOCATION_KEY,STREET,CITY,PROVINCE_OR_STATE,COUNTRY) values ('l3','sda','delhi','delhi','india');
--------------------------------------------------------
--  DDL for Index SYS_C008319
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008319" ON "SYSTEM"."LOCATION" ("LOCATION_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOCATION" MODIFY ("LOCATION_KEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOCATION" ADD PRIMARY KEY ("LOCATION_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
